### ISSUE TITLE
Visualization Questions

### ISSUE THREAD

**Issue by Kamel-schbock** [google/next-prediction#19]
Hey, 
I have question about the visualization. After i train and test the model how can i see the visualization on real video?
If i want to use this code to predict for example the motion path of human's arm, is it possible? What should i take into account?
Thanks
Best Regards

**Comment by JunweiLiang** [comment]
Please refer to #4

**Comment by JunweiLiang** [comment]
To predict the motion of human's arm, you will need to have annotations of the human poses/keypoints, etc, instead of positions of their feet. The model would still work reasonably well.
This [paper](http://openaccess.thecvf.com/content_ICCV_2019/papers/Wang_Imitation_Learning_for_Human_Pose_Prediction_ICCV_2019_paper.pdf), for example, predicts human poses.

**Comment by isaryo** [comment]
You may release that part of the code in the future?
I want to see the code.

**Comment by JunweiLiang** [comment]
No. However, #4 includes a critical part of the code I used for visualization.

**Comment by Kamel-schbock** [comment]
Could you please tell me where i should specify the human's poses instead of feet in your code ?

Why you can't release that part of the code 😅? Maybe it is hard for us if we don't really know the structure of your code... if there is no visualization how can i ensure the efficiently of this algorithm😅
Thanks 😊
