### ISSUE TITLE
Grid size

### ISSUE THREAD

**Issue by jagmonroy** [google/next-prediction#8]
Hi, I hope you be fine. Thanks a lot for the code!

In the experiments the grid size is (64, 51), I would like to know if there is any reason. I'm curious, did you try with other sizes? I don't have idea/intuition of how could change the results varying the grid size; maybe with a bigger size the model's potential increase but the training process is harder; by other hand, I don't know what size could be considered to small.

**Comment by JunweiLiang** [comment]
In the ActEV experiments the scene semantic segmentation feature input is resized to (64, 36). The grid sizes are two scales, of (32, 18) and (16, 9). I haven't tried other sizes. I chose these sizes since they could produce features with reasonable storage (we need to save scene semantic feature almost every frames) and the models should fit into the GPU with reasonable batch size. Also, they look reasonable (one person per grid) to me. Here is a visualization of 16x9 grid:

![grid1](https://user-images.githubusercontent.com/22200250/62984985-30c93380-bdea-11e9-8065-9054ee2f427e.jpg)

And then I used similar grids for ETH/UCY experiments.
